### PR TITLE
Make Transport and SyncTransport implement java.io.Closable

### LINKED ISSUE #76: implement AutoCloseable in Transport
I think implementation of `Socket `should implement interface `AutoCloseable `  (introduced in Java 7) to make it possible to use try-with-resources idiom.

What do you think?

### PR DESCRIPTION
**Pull request by janosvitok**
This PR is based on #88, I will rebase/update this one when that one is resolved.

Fixes #76.

### CODE REVIEW

**Comment by vidstige** [comment]
Why the "WIP" prefix? Should I review this? 🤔

**Comment by janosvitok** [comment]
I've rebased this, it's ready to merge now. After this is merged, #86 can be rewritten to use try-with-resources.

**Comment by vidstige** [comment]
But looks very clean otherwise. Thank you!

**Comment by janosvitok** [comment]
The idea behind the RawSyncTransport is here: https://github.com/vidstige/jadb/pull/86#discussion_r200099823

Maybe SyncTransport (the one that does not own nor close the streams) should stay SyncTransport, and the new class that owns and closes its streams should be called ClosableSyncTransport.

The problem here is that one version can live with DataInput/DataOutput interfaces (that do not implement Closable) and the other needs DataInputStream/DataOutputStream classes (that implement Closable).

If they are not split in two classes, either it needs to use DataInputStream/DataOutputStream instead of DataInput/DataOutput, or have two sets of variables (DI/DO would be filled always, DIS/DOS only when they are owned by the class, and should be closed). It seemed to me that two classes are cleaner, though I'm not too happy with the name...

I will try to add some unit tests...

**Comment by vidstige** [comment]
@janosvitok alright, can't you access the underlying streams via `DataInput`/`DataOutput`? That would have been sweet. If not, keeping two sets variables (four in total) does not seem to bad in my opinion? How do you feel about that? A bit more coupled, but one less class. If you feel it's too messy, lets go with two classes like it stands right now. But a unit test, that uses the autoclosable syntax would be nice.

**Comment by janosvitok** [comment]
Let's go with #95.

**Pull request closed without merging**
