### PR TITLE
 vidstige/jadb#34 implemented

### PR DESCRIPTION
**Pull request by SKART1**
#34 implemented

### CODE REVIEW

**Comment by vidstige** [comment]
Great! Can you explain a bit more on how this works and the benefit? I'm no Maven expert here..

**Comment by vidstige** [comment]
For future, please add a descriptive commit message, rather than just linking to github issuse. You may link it as well of course 👍

**Comment by SKART1** [comment]
Comment about commit description is just - will write more about code

What about maven:
1. Dependencies
   * Maven stores dependencies in special repositories (for example https://mvnrepository.com/)
   * Each dependency has `groupId`, `artifactId` and `vesion` - and dependencies are defined in `pom.xml` - xml file which in declarative style describe structure of the project

2. Assemble process in maven
   * Assemble process in maven has lifecycle stages. Plugins (which are also defined in `pom.xml` and also have versions) can add some additional actions and steps

3. Version plugin is a plugin which can:
 * Create report about all  new versions available in maven repositories for both dependencies and maven plugins
 * Update them himself (mvn versions:use-latest-versions and so on) automatically
 

So I think this plugin is not vital but make process of updating easier =)


P.S. For example with have not the latest version of `junit` - by typing `mvn versions:use-latest-versions` in terminal you are able to get latest easily

**Comment by vidstige** [comment]
Alright, cool! Could you perhaps add a short text, or even a script, with how one would build and update the package in a repository? Perhaps you can just plop the command line you use yourself in a `.sh` file or such?

**Comment by SKART1** [comment]
`sh` script may be not the best solution - cause maintainers may use Windows for example where sh files will not work

May write a wiki page, or put comments in `pom.xml` file of how to use this plugin

**Comment by vidstige** [comment]
Yeah, but at least they can open the sh file and perhaps guess how to run the command on windows. Putting it in either README.md or a new .md file also works. Comment in actual `pom.xml` also sounds great. There is no wiki for simplicity right now.

**Comment by SKART1** [comment]
Added to pom.xml

**Comment by vidstige** [comment]
Thanks man

**Pull request merged**
