### PR TITLE
#84 PackageManager problems: Fixes issue 1 & 2

### PR DESCRIPTION
**Pull request by smieras**
Could not reproduce and figure out the actual issue with 3, so this is a PR for the first two.

### CODE REVIEW

**Comment by vidstige** [comment]
Thank you very much for the pull request. The two tests seem a bit strange. Instead of testing private implementation details, we should test the public interface - Is the `"-l"` part sent to the device? See my example on how to do this. Note, havn't tried that code, it's more of an example of my thought here.

**Comment by smieras** [comment]
@vidstige Thanks for the review and tips. Will implement your improvements tomorrow. 
Reason for reflection testing is simply that I am somewhat unfamiliar with the inner workings of the full system, hence the testing of just that particular method. However, I totally agree that reflection testing is less desirable.

**Comment by vidstige** [comment]
You're correct, it would test the end-to-end behavior of the source code so the System Under Test (SUT) would in this case be several classes instead of a single class. This is normal and makes the test more helpful, as you can refactor and they will help you confident everything still works. My general rule of thumb is, if you refactor you should not have to change tests, but if you add feature/fix bugs you should have to change/add test. :-) 

Anyway, my example code does not work as you say because `installWithOptions` does not return anything.  However, the variable contains the return was not used either. In fact it should just be like this `m.installWithOptions(new File('/app.apk'), PackageManager.WITH_FORWARD_LOCK);`

It may look stange as nothing is asserted, however, if a command line that was not setup to be expected is issued, the test will fail. It should be something like this.

```java
@Test
public void testWithForwardLock() thows Exception {
    server.expectShell(DEVICE_SERIAL, "pm install -l /tmp/.apk"); // <-- put in actual expected shell command here. :-)

    //Act
    new PackageManager(device).installWithOptions(new File('/app.apk'), PackageManager.WITH_FORWARD_LOCK);
}
```

I understand if you don't want to fiddle with the unit tests anymore. :-) This code was not tested before so it's no matter. If you want to have another go at the unit test I'll hold back the merge, otherwise I'll merge this within a few days. Thank you very much for your contribution. :bowing_man:

**Comment by smieras** [comment]
@vidstige 
The closest I got to a working unit test was this piece of code:

```
    @Test
    public void testWithForwardLock() throws Exception {
        //Arrange
        folder.newFolder("tmp");
        final File temporaryFile = folder.newFile("app.apk");
        final PackageManager pm = new PackageManager(device);

        server.expectShell(DEVICE_SERIAL, "pm install -l /tmp/.apk");
        server.expectPush(DEVICE_SERIAL, new RemoteFile("/sdcard/tmp/" + temporaryFile.getName())).withContent("");

        //Act
        pm.installWithOptions(temporaryFile, Collections.singletonList(PackageManager.WITH_FORWARD_LOCK));
    }
```

With the folder being:

```
@Rule
public TemporaryFolder folder = new TemporaryFolder();
```
Unfortunately the Stream gets caught in an infinite while loop on rule 17. The same issue arises when the already present "Tiniest Smallest APK ever.apk" is used.

I give up, mea culpa.

**Comment by vidstige** [comment]
Right, the file is first copied, so that needs to be mocked out somehow. The infinite loop should probably also be fixed also. One thing at a time. Thanks for trying so hard!

**Pull request merged**
